version: '2'
services:
  app:
    # Containers
    build: .
    image: renju-parallel
    container_name: renju-parallel

    # Networking
    network_mode: "bridge"
    ports:
      - "127.0.0.1:8000:8000"
